### ISSUE TITLE
Was this meant to be hardcoded for testing?

### ISSUE THREAD

**Issue by rkmiller131** [Omega-outlet/FEC#48]
The productId was just hardcoded to 40353, but when I deconstructed your currentProductID prop and put that in your useEffect dependency array, everything worked so this was probably just for testing, yeah?

Also, are you only ever pulling down 100 questions? Some things to consider might be incrementing the page upon 'see more questions' button being clicked and running out of questions to display - increment the page and do another axios call to append the next page of questions to your current filteredList

https://github.com/Omega-outlet/FEC/blob/d2b4c0accef85526e43a98f4214cff99335a7fcc/client/src/components/QuestionsAndAnswers/QuestionsAndAnswers.jsx#L7-L17

<img width="517" alt="Screenshot 2023-08-19 at 12 50 54 PM" src="https://github.com/Omega-outlet/FEC/assets/21061780/20023dee-268e-4608-a64e-07673b86bed2">

**Comment by ESC8504** [comment]
Thanks, I hardcoded the ID just for testing.
