### ISSUE TITLE
Inline Styles vs Styled Components

### ISSUE THREAD

**Issue by rkmiller131** [Omega-outlet/FEC#50]
In an ideal world, the whole project would be in sync with the styling format (and for the most part it really is!) 
But seeing inline styling without using styling components in just this section really makes it stand out as being made by a different person.

And this is just a neutral comment - you don't *have to use styled components just because others are, but if it was a group decision to do so then it might be good to start out with that (for future projects)

Side note - button type is submit over just being a regular button?

https://github.com/Omega-outlet/FEC/blob/d2b4c0accef85526e43a98f4214cff99335a7fcc/client/src/components/RatingsAndReviews/ReviewList.jsx#L5-L23

**Comment by bgomez9212** [comment]
Yeah I started with inline styling on some components, but when I got to the graph component it got really repetitive so I forced myself to take a moment and learn styled components, so in-line stuff is either stuff I did before learning styled components or one or two lines of styling that I didn't think a styled-component would be necessary. However it does make sense to have the same type of styling all over the project, so I can look into refactoring to match the rest of the project.

I did wind up changing that button type in my PR from last night/merged this morning after noticing it was submit. I think I tried "click" as a type then defaulted to submit when the linter rejected it.
