### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by rkmiller131** [Omega-outlet/FEC#52]
This looks a lot like the beginnings of the React sprint from week 3

https://github.com/Omega-outlet/FEC/blob/1e8f6880d1bdcacb223b799d785c1f71b6c90097/client/src/components/RatingsAndReviews/NewReview.jsx#L47-L97

// Exercise before Recast.ly:

![Screenshot 2023-08-19 at 2 25 26 PM](https://github.com/Omega-outlet/FEC/assets/21061780/cb4b9420-c503-4a14-9fc6-4f7fd5b8ae67)

Remember your training! Let's map :)

![Screenshot 2023-08-19 at 2 25 45 PM](https://github.com/Omega-outlet/FEC/assets/21061780/735bf393-52d5-4bcb-81c5-f038d2687c1b)

That said, I know first hand how tricky mapping radio buttons can be (maybe it's just me, but this was one of my biggest tech challenges 😂). There is a way, and it is a little frustrating. So much so that I decided to do a gigantic radio button form with my MVP so that they wouldn't conquer me.

**Comment by bgomez9212** [comment]
Thank you for these examples! I'm sure its obvious by now but I really did a bare-bones writing of these components to start with. Now half of this week has been going back through, starting at the top-most component, and being more meticulous with my code. So basically creating a bunch of tech debt for myself, just to get the components rendering in the layout/style I was hoping to achieve. Radio buttons definitely took some additional research!
