### ISSUE TITLE
Nitpicky Error Handling

### ISSUE THREAD

**Issue by rkmiller131** [Omega-outlet/FEC#54]
Even though linter wants more, I would at least handle catching errors with a console log.

https://github.com/Omega-outlet/FEC/blob/1e8f6880d1bdcacb223b799d785c1f71b6c90097/client/src/components/RatingsAndReviews/RatingsAndReviews.jsx#L21

**Comment by bgomez9212** [comment]
I will add some console logs, and you're right the reason its like this is the linter being upset with the console logs.
